export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_LOGIN_STATE_TO_TRUE = 'SET_LOGIN_STATE_TO_TRUE';
export const SET_LOGIN_STATE_TO_FALSE = 'SET_LOGIN_STATE_TO_FALSE';


export const SET_CONNECTION_ID = 'SET_CONNECTION_ID'


export const SET_PRODUCT_REQUESTED_DATA = 'SET_PRODUCT_REQUESTED_ID'
export const SET_BRAND_AND_MODELS_DATAS = 'SET_BRAND_AND_MODELS_DATAS'


export const SET_MOST_POPULAR_PRODUCTS = 'SET_MOST_POPULAR_PRODUCTS'



export const SET_USER_FAVORITE_PRODUCTS = 'SET_USER_FAVORITE_PRODUCTS'

export const ADD_USER_FAVORITE_PRODUCT = 'ADD_USER_FAVORITE_PRODUCT'
export const REMOVE_USER_FAVORITE_PRODUCT = 'REMOVE_USER_FAVORITE_PRODUCT'