export const LOGIN_SUCCEDED = 'LOGIN_SUCCEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_LOGIN_STATE_TO_TRUE = 'SET_LOGIN_STATE_TO_TRUE';
export const SET_LOGIN_STATE_TO_FALSE = 'SET_LOGIN_STATE_TO_FALSE';

export const INIT_APP_DATA = 'INIT_APP_DATA';

export const SET_CONNECTION_ID = 'SET_CONNECTION_ID'
export const SET_PRODUCT_REQUESTED_DATA = 'SET_PRODUCT_REQUESTED_ID'

export const SET_USER_FAVORITE_PRODUCTS = 'SET_USER_FAVORITE_PRODUCTS'
export const ADD_USER_FAVORITE_PRODUCT = 'ADD_USER_FAVORITE_PRODUCT'
export const REMOVE_USER_FAVORITE_PRODUCT = 'REMOVE_USER_FAVORITE_PRODUCT'


export const SET_LANG = 'SET_LANG';
export const SET_CURRENCY = 'SET_CURRENCY'

export const SET_INVENTORY_CURRENT_PAGE = 'SET_INVENTORY_CURRENT_PAGE'

export const SET_PRICE = 'SET_PRICE'


export const ADD_A_NEW_MESSAGE_NOTIFICATION = 'ADD_A_NEW_MESSAGE_NOTIFICATION'
export const RESET_NEW_MESSAGE_NOTIFICATION = 'RESET_NEW_MESSAGE_NOTIFICATION'